### ISSUE TITLE
Send API not working

### ISSUE THREAD

**Issue by ore-codes** [prime-labs/smtpexpress-client-js#1]
Send API is not working. Same with Quick Send feature on the website.

![Screenshot 2024-02-04 at 04-40-58 Doc-care](https://github.com/prime-labs/smtpexpress-client-js/assets/55947046/b0b538c1-7089-4857-9fd7-d0351816d407)

![Screenshot 2024-02-04 044406](https://github.com/prime-labs/smtpexpress-client-js/assets/55947046/a29463fc-f501-469a-a3ba-a0224cb7ebf7)

**Comment by smtpexress** [comment]
Hi @Quodline, when using our internal smtp servers, you can only send emails from the provided sender address which can be found under your project settings.

More information here: https://smtpexpress.com/docs/introduction/#creating-a-project
